export interface Cliente {
    cliente?:number;
    nombre?:string;
    direccion?:string;
    dni?:number;
    cuit?:number;
    cod_iva?:number;
    cod_ven?:number;
    cod_zona?:number;
    tipoiva?:string;
    vendedor?:string;
    zona?:string;
    telefono?:string;
    estado?:string;
    idcli?:number;
    id_cli?:number;
    fecha?:any;
    hora?:any;
}